### ISSUE TITLE
Youtube video

### ISSUE THREAD

**Issue by krava77** [Alroniks/modx-videocast#1]
Hello.
great work! I have one question, can i use youtube video with your component?

**Comment by alroniks** [comment]
Hi. Actually no. I used plugins for different video types before but removed it to simplify code and component. But component does not provide video player in the package so you can use video player that supports youtube videos and insert link to youtube video into source field. Also, you can implement any logic with objects in your code. Note, that this component does not even in betta, mostly alpha version. It used in production on my website but BC not guaranteed.

**Comment by krava77** [comment]
Thank you for the quick answer.
I need only backend part for adding videos to the site. But i can't save video. Also I don't see synchronous button and when I try to save video I get error: "Невозможно сохранить видео. Исправьте значения полей и попробуйте снова."
How can resolve this issue?

**Comment by alroniks** [comment]
Have you filled out description field on the second tab? I don't remember exactly, but it seems that it also required. Ans all fields with errors should be marked by the red border.

**Comment by krava77** [comment]
you're right! I did not fill description field, because I did not see this tab :) . Lexicon file is not configured for english version.  now is ok. 
Seems the last question. How can I display Sync button and where should I add handler code for this button to make request  on youtube or vimeo?
Thank you.

**Comment by alroniks** [comment]
In the current (latest) version, you can not. These plugins were removed, with all processors. So one way to fill video metadata (properties) now - to make it manually. Maybe I will return this functions in the future, but not sure yet.
